@startuml
start
:Get Orders by work no event status ERROR;
fork
    :Get Products by ids;
fork again
    :Get Parties by ids;
fork again
    :Get Policies by ids;
end merge
:Aggregate Products, Parties and Policies to Orders;
stop
@enduml