@startuml
!include https://raw.githubusercontent.com/chavp/data-modeling/refs/heads/master/MTI/InsurancePlatform/share_plantUML/system-colors.puml

start
ORDERS:Update Order information and work of validattion result request;
fork
    PRODUCTS:Save Products;
fork again
    PARTIES:Save Parties;
fork again
    POLICIES:Save Policies;
end merge
ORDERS:Aggregate Products, Parties and Policies to Orders;
stop
@enduml