@startuml
!include https://raw.githubusercontent.com/chavp/data-modeling/refs/heads/master/MTI/InsurancePlatform/share_plantUML/system-colors.puml

start
PARTIES:Save Parties client;
ORDERS:Update Orders work Client end date time;
stop
@enduml