@startuml
!include https://raw.githubusercontent.com/chavp/data-modeling/refs/heads/master/MTI/InsurancePlatform/class/domains-class.puml

!define ENTITIES #87c98dff
!define TYPES #a7e0acff
!define VALUES #c7e4c9ff

package "Mti.Products.Types" as TypesPkg TYPES {
    class ProductCategory <<ProductCategories>> {
        Index = Code *
        ...
        {static} +Insured: string = "MOTOR"
        {static} +MtiOriginal: string = "MTI_ORIGINAL"
    }
}

@enduml